FROM node:22-alpine AS builder
WORKDIR /app
# COPY package*.json ./
COPY package.json ./
RUN npm i
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
# COPY package*.json ./
COPY package.json ./
RUN npm i --omit=dev
COPY --from=builder /app/dist ./dist
EXPOSE 3051
CMD ["node", "dist/main"]
